service: backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

plugins:
  - serverless-iam-roles-per-function

functions:
  createCertificate:
    handler: api/create.certificate
    environment:
      CERTIFICATE_TABLE_NAME: !Ref certificationTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt certificationTable.Arn

    events:
      - http:
          method: POST
          path: /createCertificate
          cors:
            origin: "*"
            headers: ${self.custom.allowedHeaders}

resources:
  Resources:
    certificationTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "certificationTable"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          - AttributeName: "certificationId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "certificationId"
            KeyType: "HASH"
